require:
  - 'rubocop-rails'
  - 'rubocop-rspec'

AllCops:
  Exclude:
    - 'api/db/**/*'
    - '**/bin/**/*'
    - 'web/node_modules/**/*'
    - '--git-common-dir/**/*'
  NewCops: enable
  TargetRubyVersion: 2.7

RSpec:
  Include:
    - '**/*_spec.rb'
    - '**/spec/**/*'

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/ExtraSpacing:
  Enabled: false

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/LineLength:
  Max: 119

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - '**/spec/**/*.rb'

Naming/VariableNumber:
  EnforcedStyle: snake_case

Rails:
  Enabled: true

Rails/ContentTag:
  Enabled: false

Rails/HttpPositionalArguments:
  Include:
    - 'spec/**/*'

Rails/Output:
  Exclude:
    - 'config/**/*'

Rails/RenderInline:
  Enabled: false

RSpec/DescribedClass:
  SkipBlocks: true

RSpec/ExpectChange:
  EnforcedStyle: block

Style/Documentation:
  Enabled: false
